trigger: none
pr:
  branches:
    include:
      - develop
    exclude:
      - feature/*

strategy:
  matrix:
    dotnet-8.0.0:
      vesrion: '8.0.200'
    dotnet-8.0.1:
      vesrion: '8.0.201'

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    inputs:
      version: '$(vesrion)'
      installationPath: $(Agent.ToolsDirectory)/dotnet
      
  - task: DotNetCoreCLI@2
    displayName: Testes
    inputs:
      command: 'test'
      projects: 'tests/unitTests/unitTests.csproj'
      workingDirectory: '$(Pipeline.Workspace)'

  - task: PublishTestResults@2
    displayName: 'Resultados'
    inputs:
      testResultsFormat: 'XUnit'
      testResultsFiles: '*.trx'
      searchFolder: '$(Agent.TempDirectory)'