name: ci-dotnet-workflow
on: 
  pull_request:
    branches:
      - develop
      
permissions:
  checks: write
  pull-requests: write
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - run: dotnet test tests/unitTests/unitTests.csproj --logger trx --results-directory test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/*.trx