name: ci-dotnet-workflow
on: 
  pull_request:
    branches:
      - develop

permissions:
  checks: write
  pull-requests: write

jobs:
  check-application:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     dotnet: ['8.0.200', '8.0.201']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Executando os testes
        run: dotnet test tests/unitTests/unitTests.csproj --logger trx --results-directory test-results

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHU_USERNAME }}
          password: ${{ secrets.DOCKERHU_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: afroboxcode/calculator-githubactions:latest
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: 'Testes'
          files: |
            test-results/*.trx